main: net.simplyrin.notgriefing.NotGriefing
name: NotGriefing
version: 1.3.0
authors: [Sui(@Sui_pw),SimplyRin]
api-version: 1.14
commands:
  notgriefing:
    usage: /notgriefing <reload>
    description: NotGriefing main command.