main: net.simplyrin.notgriefing.Main
name: NotGriefing
version: 1.0
authors: [Sui(@Sui_pw),SimplyRin]
commands:
  notgriefing:
    usage: /notgriefing <reload>
    description: NotGriefing main command.
